### ISSUE TITLE
Connections: consistency in config keys

### ISSUE THREAD

**Issue by expobrain** [revolut-engineering/data-libs#23]
Should the schema name in the config be consistent between PostgreSQL and Exasol definitions?

At the moment in PotgreSQL is called `dbname` and in `Exasol` is called `schema` which is confusing.

Shall we just use the name `schema` for database schema names?

**Comment by foxyblue** [comment]
I thought of this too, but it depends on the direction of this library.

If we are to include things like GCS/S3 buckets as other "Connections" it's probably better to leave the implementation specific names in the config. And indication the required fields per implementation.

Alternatively we can supply a "schema" which is translated to "bucket". But it depends on which is more confusing.

**Comment by expobrain** [comment]
How likely and how soon are we gonna implement that? 

Because if this if very unlikely or it will happen sometimes in the future I prefer to be consistent now.

**Comment by foxyblue** [comment]
This already exists in the connections we are deprecating.

**Comment by expobrain** [comment]
Ok, so make sense to use database-specific keys, closing this issue
