### ISSUE TITLE
Connections: should be _env be supported everywhere

### ISSUE THREAD

**Issue by expobrain** [revolut-engineering/data-libs#28]
Should be `_env:<env_variable>` pattern be supported everywhere in the config file and not only for user and password?

**Comment by foxyblue** [comment]
It is supported everywhere

**Comment by expobrain** [comment]
My question was more for `dsn`. 

I found out that you cannot just say `_env:HOST:8564`, the port part will be dropped.

**Comment by foxyblue** [comment]
Everything after the second `:` is intended to be default for that property. e.g:

```
dsn: _env:EXASOL_DSN:localhost:8080

>>> c.dsn
'localhost:8080'
```

My decision to use `dsn` over `host:port` was to allow us to have a standard use of the dsn string when attempting to resolve failovers, without connecting to incorrect|redundant `port:host` combinations.

**Comment by expobrain** [comment]
Cool!

I reckon that this behaviour should be documented in the README
